# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ptsm_gp_sample <- function(y, designMatrix, betaPriorMean, betaPriorVariance, variancePriorAlpha, variancePriorBeta, tauSquaredPriorAlpha, tauSquaredPriorBeta, nGPBases) {
    .Call('positivemixtures_gpSample', PACKAGE = 'positivemixtures', y, designMatrix, betaPriorMean, betaPriorVariance, variancePriorAlpha, variancePriorBeta, tauSquaredPriorAlpha, tauSquaredPriorBeta, nGPBases)
}

#' @export
rgev <- function(n, mu, sigma, xi) {
    .Call('positivemixtures_rgevVector', PACKAGE = 'positivemixtures', n, mu, sigma, xi)
}

.estimatePwm <- function(x, r) {
    .Call('positivemixtures_estimatePwm', PACKAGE = 'positivemixtures', x, r)
}

#' @export
gevPwmEstimate <- function(x) {
    .Call('positivemixtures_gevPwmEstimate', PACKAGE = 'positivemixtures', x)
}

#' @export
gevPwmEstimateConstrained <- function(x, supportLim) {
    .Call('positivemixtures_gevPwmEstimateConstrained', PACKAGE = 'positivemixtures', x, supportLim)
}

.ptsm_hmm_sample <- function(nSamples, burnIn, yR, distributionNames, priors, samplingSchemes, zStart, thetaStart, thetaSampleThinning = 1L, zSampleThinning = 0L, yMissingSampleThinning = 0L, verbose = 0L) {
    .Call('positivemixtures_hmmSample', PACKAGE = 'positivemixtures', nSamples, burnIn, yR, distributionNames, priors, samplingSchemes, zStart, thetaStart, thetaSampleThinning, zSampleThinning, yMissingSampleThinning, verbose)
}

.ptsm_independent_sample <- function(nSamples, burnIn, yR, distributionNames, priors, samplingSchemes, zStart, distributionsStart, distributionSampleThinning = 1L, pSampleThinning = 1L, zSampleThinning = 0L, yMissingSampleThinning = 0L, progress = FALSE) {
    .Call('positivemixtures_independentSample', PACKAGE = 'positivemixtures', nSamples, burnIn, yR, distributionNames, priors, samplingSchemes, zStart, distributionsStart, distributionSampleThinning, pSampleThinning, zSampleThinning, yMissingSampleThinning, progress)
}

.ptsm_logistic_ergodic_p <- function(deltaSamplesR, zSamplesR, z0SamplesR, designMatrixR, order) {
    .Call('positivemixtures_logisticErgodicP', PACKAGE = 'positivemixtures', deltaSamplesR, zSamplesR, z0SamplesR, designMatrixR, order)
}

.ptsm_logistic_predicted_p <- function(levels, order) {
    .Call('positivemixtures_logisticPredictedP', PACKAGE = 'positivemixtures', levels, order)
}

.ptsm_logistic_moments <- function(distributionSamplesR, levels, order, conditionOnPositive) {
    .Call('positivemixtures_logisticMoments', PACKAGE = 'positivemixtures', distributionSamplesR, levels, order, conditionOnPositive)
}

.ptsm_logistic_generate <- function(deltaR, explanatoryVariablesR, distributionParameters, distributionNames, order) {
    .Call('positivemixtures_logisticGenerate', PACKAGE = 'positivemixtures', deltaR, explanatoryVariablesR, distributionParameters, distributionNames, order)
}

.ptsm_logistic_sample_mpi <- function(nSamples, burnIn, panelY, panelDesignMatrix, order, distributionNames, priors, samplingSchemes, panelZStart, panelZ0Start, thetaStart, panelDeltaStart, deltaFamilyMeanStart, deltaFamilyVarianceStart, deltaDesignMatrix, thinning, verbose = 0L, progress = FALSE) {
    .Call('positivemixtures_logisticSampleMPI', PACKAGE = 'positivemixtures', nSamples, burnIn, panelY, panelDesignMatrix, order, distributionNames, priors, samplingSchemes, panelZStart, panelZ0Start, thetaStart, panelDeltaStart, deltaFamilyMeanStart, deltaFamilyVarianceStart, deltaDesignMatrix, thinning, verbose, progress)
}

.ptsm_logistic_sample <- function(nSamples, burnIn, panelY, panelDesignMatrix, order, distributionNames, priors, samplingSchemes, panelZStart, panelZ0Start, thetaStart, panelDeltaStart, deltaFamilyMeanStart, deltaFamilyVarianceStart, deltaDesignMatrix, thinning, verbose = 0L, progress = FALSE) {
    .Call('positivemixtures_logisticSample', PACKAGE = 'positivemixtures', nSamples, burnIn, panelY, panelDesignMatrix, order, distributionNames, priors, samplingSchemes, panelZStart, panelZ0Start, thetaStart, panelDeltaStart, deltaFamilyMeanStart, deltaFamilyVarianceStart, deltaDesignMatrix, thinning, verbose, progress)
}

.ptsm_logistic_sample_y <- function(panelExplanatoryVariablesR, panelDeltaSampleR, panelZ0SampleR, distributionSampleR, distributionNames) {
    .Call('positivemixtures_logisticSampleY', PACKAGE = 'positivemixtures', panelExplanatoryVariablesR, panelDeltaSampleR, panelZ0SampleR, distributionSampleR, distributionNames)
}

benchmarkLogistic <- function(nDeltas, nValues, nIterations) {
    invisible(.Call('positivemixtures_benchmarkLogistic', PACKAGE = 'positivemixtures', nDeltas, nValues, nIterations))
}

rpolyagamma <- function(length, n, z) {
    .Call('positivemixtures_rpolyagammaVector', PACKAGE = 'positivemixtures', length, n, z)
}

thinplate_basis_2d <- function(X, nBases) {
    .Call('positivemixtures_thinplateBasis2d', PACKAGE = 'positivemixtures', X, nBases)
}

.levels_to_list_integer_vector <- function(x, xLevels) {
    .Call('positivemixtures_levelsToListIntegerVector', PACKAGE = 'positivemixtures', x, xLevels)
}

.levels_to_list_numeric_vector <- function(x, xLevels) {
    .Call('positivemixtures_levelsToListNumericVector', PACKAGE = 'positivemixtures', x, xLevels)
}

.levels_to_list_numeric_matrix <- function(x, xLevels) {
    .Call('positivemixtures_levelsToListNumericMatrix', PACKAGE = 'positivemixtures', x, xLevels)
}

