# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rgev <- function(n, mu, sigma, xi) {
    .Call('threecomponentmixture_rgevVector', PACKAGE = 'threecomponentmixture', n, mu, sigma, xi)
}

.estimatePwm <- function(x, r) {
    .Call('threecomponentmixture_estimatePwm', PACKAGE = 'threecomponentmixture', x, r)
}

#' @export
gevPwmEstimate <- function(x) {
    .Call('threecomponentmixture_gevPwmEstimate', PACKAGE = 'threecomponentmixture', x)
}

#' @export
gevPwmEstimateConstrained <- function(x, supportLim) {
    .Call('threecomponentmixture_gevPwmEstimateConstrained', PACKAGE = 'threecomponentmixture', x, supportLim)
}

.threeComponentMixtureHMMSample <- function(nSamples, burnIn, y, prior, zStart, thetaStart) {
    .Call('threecomponentmixture_threeComponentMixtureHMMSample', PACKAGE = 'threecomponentmixture', nSamples, burnIn, y, prior, zStart, thetaStart)
}

.threeComponentMixtureSample <- function(nSamples, burnIn, y, prior, zStart, thetaStart) {
    .Call('threecomponentmixture_threeComponentMixtureSample', PACKAGE = 'threecomponentmixture', nSamples, burnIn, y, prior, zStart, thetaStart)
}

